const tags = {
    ANIMALS: "Animals",
    ATTIC: "Attic",
    BASEMENT: "Basement",
    BATHROOM: "Bathroom",
    BEDROOM: "Bedroom",
    CLEAN_UP: "Clean up",
    ELECTRIC: "Electrical",
    FRIENDS_FAMILY: 'Friends & Family',
    FOYER: "Foyer",
    GARAGE: "Garage",
    IMPROVEMENTS: "Improvements",
    KITCHEN: "Kitchen",
    LITTLE_MOMENTS: "Little Moments",
    LIVINGROOM: "Livingroom",
    MOVE_IN: "Move In",
    PLANTS: "Plants",
    PLUMBING: "Plumbing",
    PROJECTS: "Projects",
    REPAIRS: "Repairs",
    UTILITIES: "Utilities",
    YARD: 'Yard',
}